server:
  port: 8901

spring:
  application:
    name: easy-pay
  profiles:
    active: dev
  mail:
    protocol: smtps
    host: smtp.163.com
    port: 465
    username: ''
    password: ''

logging:
  charset:
    console: UTF-8
    file: UTF-8
  pattern:
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(---){faint} %clr([%20.20t]){faint} %clr(%-50.50logger{49}){cyan} %clr(:){faint} [%X{TRACE_ID}] %m%n%wEx'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} %5p --- [%20.20t] %-50.50logger{49} : [%X{TRACE_ID}] %m%n%wEx'
  file:
    name: log/app.log
  logback:
    rollingpolicy:
      max-history: 30
      max-file-size: 30MB
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.log

exception-notify:
  from: ''
  to:
    - chinesechain@163.com
